### PR TITLE
Fix magic number for 32-bit x86 in qemu-binfmt

### PR DESCRIPTION
**Pull request by fancsali**
In fact i386 and i486 are 32-bit architectures, hence the addressing needs to be 32-bit too. The fifth byte (0x04) in the ELF header should be 0x01 for 32-bit. At least according to the relevant Wikipedia article.

### CODE REVIEW

**Comment by jirutka** [comment]
It seems you’re right, thanks for the fix!

**Comment by fancsali** [comment]
Would this, and #23 perhaps warrant a release? So it can be updated in the
aports...

**Comment by jirutka** [comment]
Ok, done.

**Comment by nekopsykose** [comment]
it seems that this has a regression- 32-bit x86 binaries on an x86_64 host now get ran in qemu-binfmt. so, when you try run any 32-bit binary (which runs completely ok on a 64-bit host if it's static, is in flatpak (steam), ..), it gets ran via qemu-i386. for the 'flatpak in steam' case, this breaks it and it fails to start. undoing this change makes it run fine.

i suppose this should not get registered when on an x86_64 host, or perhaps have some other form of exclusion? it's wrong to run 32-bit binaries via qemu on a host that does not need qemu to run them and support 32-bit mode (i assume 32-bit arm might have the same issue).

**Comment by fancsali** [comment]
Fair point.

However, undoing the change would then mess up the use-cases, where the
host architecture is not a superset of the guest one. Or am I just assuming
that? My gut feeling is, it only worked correctly before, because the magic
number stating "64-bit i386 ELF binary" never applied.

So, in my mind, the comparison in `/etc/init.d/qemu-binfm` should be
extended from "is guest equal host" to "is guest = host OR is guest a
subset of host".

**Comment by nekopsykose** [comment]
> However, undoing the change would then mess up the use-cases, where the
host architecture is not a superset of the guest one. Or am I just assuming
that?  

not at all, it would indeed then be broken in that case instead. i'm not proposing a revert- you just have to make the check a bit smarter :)  

sadly i don't see a way to do that in the magic number itself (maybe i'm wrong?), so you'll have to make the actual loading smarter- but this change in itself is good :)  

this also isn't an issue if you don't have qemu-i386 installed. since then there is nothing to load. it's a rare case where you have that installed (who would have that on an x86_64 machine?), want to then run 32 binaries that break with it, and are also using this magic. i will probably be the only person to run into this ever :D

**Comment by PureTryOut** [comment]
I just hit this while trying to launch Steam in Flatpak on my laptop, it failed to launch because of qemu-i386. Removing it made it work again. It's going to be a bit hard to test build x86 Alpine packages on my laptop now :sweat_smile:

**Comment by nekopsykose** [comment]
if your laptop is x86_64, then you never needed qemu-i386 anyway, as the binaries just run natively. is that not the case for you?

**Comment by nekopsykose** [comment]
(well, i guess there is an unrelated abuild issue there, haha)

**Pull request merged**
